# SERVIÃ‡O SICOOB PRECISA DO CAMINHO REAL DAS KEYS NO SISTEMA

services:
  releases:
    image: zryyh/releasessync:latest
    container_name: releases-sync
    restart: unless-stopped
    env_file:
      - .env # DEFINIR .env
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
    networks:
      - pocketbase_network

  conciliations:
    image: zryyh/conciliationssync:latest
    container_name: conciliations-sync
    restart: unless-stopped
    env_file:
      - .env # DEFINIR .env
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
    networks:
      - pocketbase_network

  sicoob:
    image: zryyh/sicoobsync:latest
    container_name: sicoob-sync
    restart: unless-stopped
    env_file:
      - .env # DEFINIR .env
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
    volumes:
      - ./keys:/app/keys:ro # AQUI DEVE SER DEFINIDA O CAMINHO DAS KEYS
    networks:
      - pocketbase_network

  finpet:
    image: zryyh/finpetsync:latest
    container_name: finpet-sync
    restart: unless-stopped
    env_file:
      - .env # DEFINIR .env
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
    networks:
      - pocketbase_network

  pocketbase:
    image: zryyh/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    volumes:
      - pb_data:/pb/pb_data
      - pb_public:/pb/pb_public
    command: [ "/pb/pocketbase", "serve", "--http=0.0.0.0:8090", "--dir=/pb/pb_data", "--publicDir=/pb/pb_public" ]
    networks:
      - pocketbase_network

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "127.0.0.1:81:81"
      - "80:80"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - pocketbase_network

volumes:
  metabase_data:
    driver: local
  pb_data:
    driver: local
  finpet_logs:
    driver: local
  pb_public:
    driver: local
  npm_data:
    driver: local
  npm_letsencrypt:
    driver: local

networks:
  pocketbase_network:
    driver: bridge